# Generated by Django 6.0.5 on 2026-05-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('pastor', 'Pastor'), ('elder', 'Presiding Elder'), ('administrator', 'Administrator'), ('overseer', 'Overseer'), ('shepherd_leader', 'Shepherd Leader')], max_length=30),
        ),
    ]
