# Generated by Django 6.0.5 on 2026-05-26 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_staffprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'overseer')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='members.staffprofile'),
        ),
    ]
